# Numpy

**What is an array?**

An array is the data structure of NumPy library. The elements are all of the same type, referred to as the array dtype.

In [1]:
import numpy as np

## **Different Methods of Creating an Array**

To create a NumPy array, you can use the function `np.array()`. We initialize array inside square brackets `[]`

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])   
a

array([1, 2, 3, 4, 5, 6])

Creating array filled with 0s or 1s

In [3]:
np_zero = np.zeros(3)  
print(np_zero)
np_one = np.ones(2)
print(np_one)

[0. 0. 0.]
[1. 1.]


Creating an array with a range of evenly spaced intervals. `np.arange(start num, end num(not included), step size)`

In [4]:
a_range = np.arange(2, 10, 2)
print(a_range)
b_range = np.arange(2, 11, 2)
print(b_range)
b_range = np.arange(2, 11, 2.5)
print(b_range)

[2 4 6 8]
[ 2  4  6  8 10]
[2.  4.5 7.  9.5]


We can also use np.linspace() to create an array with values that are spaced linearly in a specified interval: `np.linspace(start, end(included) , total numbers)`

In [5]:
a_lspce = np.linspace(0, 10, num = 5)
print(a_lspce)
b_lspce = np.linspace(0, 10, num = 4)
print(b_lspce)

[ 0.   2.5  5.   7.5 10. ]
[ 0.          3.33333333  6.66666667 10.        ]


## Sorting

In [6]:
arr1 = np.array([2, 1, 5, 3, 7, 4])
print(np.sort(arr1))
arr2 = np.array([2, -1, 5, 3, -7, 4])
print(np.sort(arr2))

[1 2 3 4 5 7]
[-7 -1  2  3  4  5]


In [4]:
# concatenate np.concatenate().
a = np.array([1, 2, 3, 4])
b = np.array([5, 6])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

# Delete elements from an array

In [5]:
# np.delete(a, index)
a = np.array([1, 2, 3])
# a[0] : index 
np.delete(a,1)

array([1, 3])

## Multi Dimention Array 

In [8]:
multi_dim = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(multi_dim.ndim) # get the no of dimentions in the array 
print(multi_dim.size) # total elements in an array 
multi_dim.shape # (row, columns)

2
8


(2, 4)

In [32]:
multi_dim = np.array(
  [
    [
      [0, 1, 2, 3],
      [4, 5, 6, 7]
    ],
    [
      [0, 2, 4, 6],
      [8, 10, 12, 14]
    ]
  ]
)
print(multi_dim.shape) # traverse from outer brackets and check dimentions (height, row, column)
print(multi_dim.ndim) # get the no of dimentions in the array
print(multi_dim.size) # total elements in an array

(2, 2, 4)
3
16


## Indexing and slicing

You may want to take a specific section of your array to use in further analysis or noperations. In Python, index always starts from 0.

In [33]:
data = np.array([1, 2, 3, 4])
print(data[3])
print(data[0:2]) # pick 1st 2 elements 0,1 index. 2 index is not included
print(data[-3:]) # pick last 3 elements in the array. 
data_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(data_2d[:2,:1]) # [row slice, column slice]

4
[1 2]
[2 3 4]
[[1]
 [4]]


In [36]:
# subset an array
data = np.array([1, 2, 3, 4])
# less than equal to 3
print(data[data<=3])
# divisible by 2
print(data[data%2 == 0])
# select elements that satisfy two conditions using the & and | operators:
print(data[(data > 2) & (data < 4)])
print(data[(data == 4) | (data == 2)])

[1 2 3]
[2 4]
[3]
[2 4]


In [35]:
# logical operators & and | can return boolean values that specify whether or not the values in an array 
# fulfill a certain condition.
data = np.array([1, 2, 3, 4, 5, 6])
gt_eq_4 = (data > 4) | (data == 4)
print(gt_eq_4)

[False False False  True  True  True]


## Basic Array operations 

In [9]:
# Addition
data = np.array([1, 2, 3])  
ones = np.ones(3, dtype = int)  # creating an array of ones 
data + ones

array([2, 3, 4])

In [39]:
# substaction 
print(data - ones)
# division 
print(data / ones)
# multiplication 
print(data * ones)

[0 1 2]
[1. 2. 3.]
[1 2 3]


In [40]:
# sum of elements in an array 
a = np.array([1, 2, 3, 4])
print(a.sum())
# multi-dimention
b = np.array([[1, 1], [2, 2]])
print(b.sum(axis = 0)) # sum across columns
print(b.sum(axis = 1)) # sum across rows

10
[3 3]
[2 4]


In [41]:
# min, max, mean and std
a = np.array([1, 2, 3, 4, 5])
# minimum in an array
print(a.min())
# maximum of an array 
print(a.max())
# mean of an array
print(a.mean())
# standard deviation of an array
print(a.std())

1
5
3.0
1.4142135623730951


In [2]:
# operations: multi - dimention array 
data = np.array([[2, 1], [3, 4]])
print(data.sum())
print(data.max())
print(data.min(axis = 0)) #minimum across column
(data.min(axis = 1)) #minimum across row

10
4
[2 1]


array([1, 3])